---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Alexa Filetered Skill"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "filtered.swagger.io"
basePath: "/v2"
tags:
- name: "interview"
  description: "Candidate Interview Information"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /interview:
    post:
      tags:
      - "interview"
      summary: "Add a new interview to the Portal"
      description: ""
      operationId: "addInterview"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Interview object that needs to be added to the Portal"
        required: true
        schema:
          $ref: "#/definitions/body_1"
      responses:
        405:
          description: "Invalid input"
      security:
      - interviewportal_auth:
        - "write:interviews"
        - "read:interviews"
      x-swagger-router-controller: "Interview"
    put:
      tags:
      - "interview"
      summary: "Update an existing interview"
      description: ""
      operationId: "updateInterview"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Interview object that needs to be added to the Portal"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
        405:
          description: "Validation exception"
      security:
      - interviewportal_auth:
        - "write:interviews"
        - "read:interviews"
      x-swagger-router-controller: "Interview"
  /pet/findByStatus:
    get:
      tags:
      - "interview"
      summary: "Finds Interviews by status"
      description: "Enter the status to get information"
      operationId: "findInterviewsByStatus"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
          default: "Pending"
          enum:
          - "Completed"
          - "pending"
          - "Incomplete"
        collectionFormat: "multi"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid status value"
      security:
      - interviewportal_auth:
        - "write:interviews"
        - "read:interviews"
      x-swagger-router-controller: "Interview"
  /interview/{interviewId}:
    get:
      tags:
      - "interview"
      summary: "Find interview by ID"
      description: "Returns a single interview information"
      operationId: "getInterviewById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "interviewId"
        in: "path"
        description: "ID of interview to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Interview not found"
      security:
      - api_key: []
      x-swagger-router-controller: "Interview"
    post:
      tags:
      - "interview"
      summary: "Updates a interview in the portal with form data"
      description: ""
      operationId: "updateInterviewWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "interviewId"
        in: "path"
        description: "ID of interview that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "name"
        in: "formData"
        description: "Updated name of the interview"
        required: false
        type: "string"
      - name: "status"
        in: "formData"
        description: "Updated status of the interview"
        required: false
        type: "string"
      responses:
        405:
          description: "Invalid input"
      security:
      - interviewportal_auth:
        - "write:interviews"
        - "read:interviews"
      x-swagger-router-controller: "Interview"
    delete:
      tags:
      - "interview"
      summary: "Deletes a interview"
      description: ""
      operationId: "deleteInterview"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "interviewId"
        in: "path"
        description: "Interview id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Interview not found"
      security:
      - interviewportal_auth:
        - "write:interviews"
        - "read:interviews"
      x-swagger-router-controller: "Interview"
securityDefinitions:
  interviewportal_auth:
    type: "oauth2"
    authorizationUrl: "http://filtered.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:interviews: "modify interviews in your account"
      read:interviews: "read your interviews"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  Interview:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      status:
        type: "string"
        description: "interview status in the store"
        enum:
        - "Completed"
        - "pending"
        - "Incomplete"
    xml:
      name: "Interview"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  body:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      status:
        type: "string"
        description: "interview status in the store"
        enum:
        - "Completed"
        - "pending"
        - "Incomplete"
    xml:
      name: "Interview"
  body_1:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      status:
        type: "string"
        description: "interview status in the store"
        enum:
        - "Completed"
        - "pending"
        - "Incomplete"
    xml:
      name: "Interview"
  inline_response_200:
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      status:
        type: "string"
        description: "interview status in the store"
        enum:
        - "Completed"
        - "pending"
        - "Incomplete"
  inline_response_200_1:
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      status:
        type: "string"
        description: "interview status in the store"
        enum:
        - "Completed"
        - "pending"
        - "Incomplete"
    xml:
      name: "Interview"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
